### ISSUE TITLE
yaml package, pyyaml?

### ISSUE THREAD

**Issue by jimmymathews** [tgbugs/orthauth#5]
Not sure why this was tagged with "FIXME",
https://github.com/tgbugs/orthauth/blob/25f89c512977cdcbd01a70c7c6afc8e0a6a9ce2a/orthauth/core.py#L16-L19
but as a first time user I did have trouble identifying the appropriate package for yaml support.
Judging from usage it looks like [pyyaml](https://pypi.org/project/PyYAML/) is the right one. If so shall this be mentioned somewhere?

**Comment by tgbugs** [comment]
Thanks you for the report.

Yes that is correct. You should be able to get pip to install the correct dependency using `pip install orthauth[yaml]` (see the python.org [tutorial](https://packaging.python.org/tutorials/installing-packages/#installing-setuptools-extras) on install extras). I will add a note to the readme about this so that it is more visible.

It is here in setup.py https://github.com/tgbugs/orthauth/blob/25f89c512977cdcbd01a70c7c6afc8e0a6a9ce2a/setup.py#L18 with the spec for the extra here https://github.com/tgbugs/orthauth/blob/25f89c512977cdcbd01a70c7c6afc8e0a6a9ce2a/setup.py#L48. For the record it is also documented here in the orthauth ebuild here https://github.com/tgbugs/tgbugs-overlay/blob/0bd2db38367353a4da29e6097e681284fcb91311/dev-python/orthauth/orthauth-9999.ebuild#L40.

With regard to the FIXME DANGERZONE it is because there is a silent failure which is suppressed (to avoid annoying messages that are impossible to turn off) and is deferred until https://github.com/tgbugs/orthauth/blob/25f89c512977cdcbd01a70c7c6afc8e0a6a9ce2a/orthauth/core.py#L326-L330. Also because I would prefer to handle support for yaml and other different formats in a more consistent and modularized/extensible way. Also originally it was because I was importing yaml at the top level https://github.com/tgbugs/orthauth/blob/3c0d9943df614f465686c00df7237baaaadc861b/orthauth/core.py#L1.

Lastly on the yaml front I do not want orthauth to support all of yaml's features due to the complexity of the yaml spec and the security issues around yaml. Thus until I find time to write a spec for the safe subset of yaml that I want to support I am using pyyaml to provide support for parsing yaml files with all its features and avoiding the formats I don't want to support by convention. This is mostly because I want the underlying formats to be portable between multiple language (e.g. I have prototypes for, elisp, common lisp, and Racket versions of orthauth and despite the fact that they all also provide yaml support via libyaml I don't want to limit the portability of the configs based on the need for an external dependency on libyaml which not all languages might have. This is particularly an issue for yaml based secret store files. Ideally I would like to be able to have the yaml "lite" format in the secrets file be parsable without any external dependencies.

Maybe more detail than you wanted, but here for reference in case the question comes up in the future.

**Comment by tgbugs** [comment]
I added a table to the readme via https://github.com/tgbugs/orthauth/commit/d8b32a05db3af5fdc9c1b5281b5daa8c6c6b502c which should address this (direct view of the rendering in the readme [here](https://github.com/tgbugs/orthauth/tree/d8b32a05db3af5fdc9c1b5281b5daa8c6c6b502c#currently-supported-config-formats)).

I'm going to go ahead and close this but let me know if you have other questions.
