### ISSUE TITLE
'current' is None

### ISSUE THREAD

**Issue by jimmymathews** [tgbugs/orthauth#7]
https://github.com/tgbugs/orthauth/blob/d8b32a05db3af5fdc9c1b5281b5daa8c6c6b502c/orthauth/core.py#L283

Simple initial import of idlib (which depends on this library, orthauth) leads to 'current' being None here, so that this line triggers an error:
'TypeError: 'NoneType' object is not subscriptable'
and the import fails.
This happened on Windows and RPi OS, but not on Ubuntu.
Most likely there is something wrong with my local environments... But it's not clear to me what in the environment orthauth is looking for in order to be able to provide basic default functionality.
Please close if I am just misunderstanding something trivial!

**Comment by tgbugs** [comment]
I'm having trouble reproducing this on windows (not WSL) and raspbian (though I am having success producing other errors). Can you provide a bit more context? For example, which python version(s) are causing the issue, if you installed from pip what is the output of `pip list | grep "\(idlib\|orthauth\)"`, and do you have a full backtrace?

The error itself happens because orthauth tries to load the config file from disk but can't find it for some reason. Does auth-config.py exist in the idlib package on the filesystem, and does `AppData/Local/idlib/config.yaml` exist? Given the nature of the bug you can't run the below, but here is what I get on my windows test system.

```python
>>> import idlib
>>> idlib.config.auth                                                          
<orthauth.core.AuthConfig object at 0x000002119FDA0A90>                        
>>> idlib.config.auth._path
WindowsPath('c:/users/tom/git/idlib/idlib/auth-config.py')                     
>>> idlib.config.auth.user_config
<orthauth.core.UserConfig object at 0x000002119FDA0F40>                        
>>> idlib.config.auth.user_config._path
WindowsPath('C:/Users/tom/AppData/Local/idlib/config.yaml') 
```

**Comment by tgbugs** [comment]
There is also a possibility that you need to run `pip install ontquery` because it is not listed in the setup.py install_requires list since it is a temporary fix on my part to avoid having to pull some of the ontquery code into idlib directly.

**Comment by jimmymathews** [comment]
Here is the full backtrace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python37\lib\site-packages\idlib\__init__.py", line 12, in <module>
    from idlib.from_oq import (Auto,
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python37\lib\site-packages\idlib\from_oq.py", line 6, in <module>
    from idlib import apis
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python37\lib\site-packages\idlib\apis\__init__.py", line 4, in <module>
    from . import protocols_io
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python37\lib\site-packages\idlib\apis\protocols_io.py", line 71, in <module>
    store_file=auth.get_path('protocols-io-api-store-file'),
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python37\lib\site-packages\orthauth\core.py", line 581, in get_path
    var = self.get(variable_name, for_path=True)
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python37\lib\site-packages\orthauth\core.py", line 668, in get
    user_variable_value = self.user_config.get_blob('auth-variables', variable_name)
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python37\lib\site-packages\orthauth\core.py", line 487, in user_config
    ac = uc.alt_config
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python37\lib\site-packages\orthauth\core.py", line 1028, in alt_config
    path = self._alt_config_path
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python37\lib\site-packages\orthauth\core.py", line 1008, in _alt_config_path
    blob = self.get_blob('alt-config')
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python37\lib\site-packages\orthauth\core.py", line 283, in get_blob
    current = current[name]
TypeError: 'NoneType' object is not subscriptable
```
'pip list' reports:
```
idlib            0.0.1.dev6
orthauth         0.0.12
```

I do have `auth-config.py`. I also have `AppData/Local/idlib/config.yaml`, but it is empty.
I have pip version `20.1.1` and python version `3.7.8`.

And yes, I did need to `pip install ontquery`.

I am on Windows 10. Perhaps it is an issue with my understanding of something basic on Windows, perhaps some sort of file permissions thing... I'm afraid I'm not very familiar with Windows.

**Comment by tgbugs** [comment]
Short version. Removing the empty `AppData/Local/idlib/config.yaml` should fix the issue. Let me know if this fixes the issue for you.

Hrm, if `AppData/Local/idlib/config.yaml` is empty (i.e., zero bytes) then that could be the source of the problem. If we hadn't already gone over the pyyaml issue I would have guess that that was related, and in fact it might be.

... a bit later

Yep! That's a bug right there.
https://github.com/tgbugs/orthauth/blob/d8b32a05db3af5fdc9c1b5281b5daa8c6c6b502c/orthauth/core.py#L568-L569

I'm guessing that the first time you ran that code it was on windows and it was when you got the yaml name error. Because of those two lines, a new empty file was created because the file was open when the name error happened, it was closed and written by the context manager. Thus the `DANGERZONE` sigh. I have fixed the bug in `write_user_config` so that an empty file cannot be created if an error occurs.

Add to all this the fact that pyyaml has a confusing behavior of returning `None` if the file it is reading is empty, and we get the behavior you are encountering.

**Comment by jimmymathews** [comment]
Good sleuthing!
I installed your new orthauth (0.0.13) from source, and I can confirm that the exception you wrote in is raised when `config.yaml` is empty.
I can also confirm that deleting `config.yaml` solved this problem. `import idlib` goes through. Also I checked the contents of the newly-created `config.yaml` and it looks normal now.
